#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

#Monitors
bspc monitor eDP-1 -d 2 4 6 8 10
bspc monitor HDMI-1 -d 1 3 5 7 9

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Rosé pine 
bspc config focused_border_color "#9ccfd8"
bspc config normal_border_color "#6e6a86"

#Fixed cursor
xsetroot -cursor_name left_ptr &

#Launch polybar 
~/.config/polybar/launch.sh &

#Wallpaper
feh --bg-fill ~/Pictures/wpp/wpp.* &

#Active picom
picom --config ~/.config/picom/picom.conf &

